// Autogenerated from Pigeon (v4.2.14), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif


/// Generated class from Pigeon.
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol JyphoonApi {
  /// Returns whether JC was inited.
  ///
  /// On **Android**:
  /// Returns **true** if JCManager.initialize() was successfully called.
  /// Otherwise, returns **false** if initialize() was not called or failed.
  func isInited() -> Bool
  /// Returns bool.
  ///
  /// Initializes the engine. It is needed to set appKey before. Otherwise, it will fail.
  func initialize() -> Bool
  /// Sets appKey in order to have access to the Jyphoon API.
  func setAppKey(appKey: String)
  /// Returns [Void].
  ///
  /// Takes [String] displayName in.
  ///
  /// Sets the name that is visible to another participant(s).
  func setDisplayName(displayName: String)
  /// Returns [bool].
  /// Sets account number. It is needed to set appKey before. Otherwise, it will fail.
  func setAccountNumber(accountNumber: String) -> Bool
  /// Returns [Void].
  ///
  /// Takes [Int] timeout in.
  ///
  /// Sets the timeout for the call request.
  func setTimeout(timeout: Int32)
  /// Returns [Boolean].
  /// Takes [String] confId in. It is the conference identifier.
  /// Takes [String] password in. It is the password for the conference.
  /// Starts the "call".
  func confJoin(confId: String, password: String) -> Bool
  /// Returns [Void].
  /// Takes [String] account in. It is the account identifier of the person you want to call.
  func setServerAddress(serverAddress: String)
  /// Returns [Void].
  /// Starts or stops to send video
  func setVideo(video: Bool)
  /// Returns [Void].
  /// Starts or stops to send audio.
  func setAudio(audio: Bool)
  /// Returns [Void].
  ///
  /// Configures the speaker mode.
  func setSpeaker(speaker: Bool)
  /// Returns [Boolean].
  /// True if the user is in the call and is not muted.
  /// Otherwise, returns false.
  func audio() -> Bool
  /// Returns [Boolean].
  /// True if the companion is in the call and is not muted.
  /// Otherwise, returns false.
  func otherAudio() -> Bool
  /// Returns [Boolean].
  /// True if the user is in the call and shares video.
  /// Otherwise, returns false.
  func video() -> Bool
  /// Returns [String].
  /// Get current user id
  func getCurrentUserId() -> String?
  /// Returns [Void].
  /// Hangs up the "call".
  func confLeave() -> Bool
  /// Returns [Boolean].
  /// True if the companion is in the call and shares video.
  /// Otherwise, returns false.
  func otherVideo() -> Bool
  /// Returns [ConferenceStatus].
  /// Returns the current conference status.
  /// It can be one of the following:
  /// - [ConferenceStatus.on]
  /// - [ConferenceStatus.off]
  /// - [ConferenceStatus.waiting]
  func confStatus() -> String
  /// Returns [Void].
  /// Switches the camera.
  func switchCamera()
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class JyphoonApiSetup {
  /// The codec used by JyphoonApi.
  /// Sets up an instance of `JyphoonApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: JyphoonApi?) {
    /// Returns whether JC was inited.
    ///
    /// On **Android**:
    /// Returns **true** if JCManager.initialize() was successfully called.
    /// Otherwise, returns **false** if initialize() was not called or failed.
    let isInitedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.isInited", binaryMessenger: binaryMessenger)
    if let api = api {
      isInitedChannel.setMessageHandler { _, reply in
        let result = api.isInited()
        reply(wrapResult(result))
      }
    } else {
      isInitedChannel.setMessageHandler(nil)
    }
    /// Returns bool.
    ///
    /// Initializes the engine. It is needed to set appKey before. Otherwise, it will fail.
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.initialize", binaryMessenger: binaryMessenger)
    if let api = api {
      initializeChannel.setMessageHandler { _, reply in
        let result = api.initialize()
        reply(wrapResult(result))
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    /// Sets appKey in order to have access to the Jyphoon API.
    let setAppKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.setAppKey", binaryMessenger: binaryMessenger)
    if let api = api {
      setAppKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let appKeyArg = args[0] as! String
        api.setAppKey(appKey: appKeyArg)
        reply(wrapResult(nil))
      }
    } else {
      setAppKeyChannel.setMessageHandler(nil)
    }
    /// Returns [Void].
    ///
    /// Takes [String] displayName in.
    ///
    /// Sets the name that is visible to another participant(s).
    let setDisplayNameChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.setDisplayName", binaryMessenger: binaryMessenger)
    if let api = api {
      setDisplayNameChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let displayNameArg = args[0] as! String
        api.setDisplayName(displayName: displayNameArg)
        reply(wrapResult(nil))
      }
    } else {
      setDisplayNameChannel.setMessageHandler(nil)
    }
    /// Returns [bool].
    /// Sets account number. It is needed to set appKey before. Otherwise, it will fail.
    let setAccountNumberChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.setAccountNumber", binaryMessenger: binaryMessenger)
    if let api = api {
      setAccountNumberChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountNumberArg = args[0] as! String
        let result = api.setAccountNumber(accountNumber: accountNumberArg)
        reply(wrapResult(result))
      }
    } else {
      setAccountNumberChannel.setMessageHandler(nil)
    }
    /// Returns [Void].
    ///
    /// Takes [Int] timeout in.
    ///
    /// Sets the timeout for the call request.
    let setTimeoutChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.setTimeout", binaryMessenger: binaryMessenger)
    if let api = api {
      setTimeoutChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let timeoutArg = args[0] as! Int32
        api.setTimeout(timeout: timeoutArg)
        reply(wrapResult(nil))
      }
    } else {
      setTimeoutChannel.setMessageHandler(nil)
    }
    /// Returns [Boolean].
    /// Takes [String] confId in. It is the conference identifier.
    /// Takes [String] password in. It is the password for the conference.
    /// Starts the "call".
    let confJoinChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.confJoin", binaryMessenger: binaryMessenger)
    if let api = api {
      confJoinChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let confIdArg = args[0] as! String
        let passwordArg = args[1] as! String
        let result = api.confJoin(confId: confIdArg, password: passwordArg)
        reply(wrapResult(result))
      }
    } else {
      confJoinChannel.setMessageHandler(nil)
    }
    /// Returns [Void].
    /// Takes [String] account in. It is the account identifier of the person you want to call.
    let setServerAddressChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.setServerAddress", binaryMessenger: binaryMessenger)
    if let api = api {
      setServerAddressChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let serverAddressArg = args[0] as! String
        api.setServerAddress(serverAddress: serverAddressArg)
        reply(wrapResult(nil))
      }
    } else {
      setServerAddressChannel.setMessageHandler(nil)
    }
    /// Returns [Void].
    /// Starts or stops to send video
    let setVideoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.setVideo", binaryMessenger: binaryMessenger)
    if let api = api {
      setVideoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let videoArg = args[0] as! Bool
        api.setVideo(video: videoArg)
        reply(wrapResult(nil))
      }
    } else {
      setVideoChannel.setMessageHandler(nil)
    }
    /// Returns [Void].
    /// Starts or stops to send audio.
    let setAudioChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.setAudio", binaryMessenger: binaryMessenger)
    if let api = api {
      setAudioChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let audioArg = args[0] as! Bool
        api.setAudio(audio: audioArg)
        reply(wrapResult(nil))
      }
    } else {
      setAudioChannel.setMessageHandler(nil)
    }
    /// Returns [Void].
    ///
    /// Configures the speaker mode.
    let setSpeakerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.setSpeaker", binaryMessenger: binaryMessenger)
    if let api = api {
      setSpeakerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let speakerArg = args[0] as! Bool
        api.setSpeaker(speaker: speakerArg)
        reply(wrapResult(nil))
      }
    } else {
      setSpeakerChannel.setMessageHandler(nil)
    }
    /// Returns [Boolean].
    /// True if the user is in the call and is not muted.
    /// Otherwise, returns false.
    let audioChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.audio", binaryMessenger: binaryMessenger)
    if let api = api {
      audioChannel.setMessageHandler { _, reply in
        let result = api.audio()
        reply(wrapResult(result))
      }
    } else {
      audioChannel.setMessageHandler(nil)
    }
    /// Returns [Boolean].
    /// True if the companion is in the call and is not muted.
    /// Otherwise, returns false.
    let otherAudioChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.otherAudio", binaryMessenger: binaryMessenger)
    if let api = api {
      otherAudioChannel.setMessageHandler { _, reply in
        let result = api.otherAudio()
        reply(wrapResult(result))
      }
    } else {
      otherAudioChannel.setMessageHandler(nil)
    }
    /// Returns [Boolean].
    /// True if the user is in the call and shares video.
    /// Otherwise, returns false.
    let videoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.video", binaryMessenger: binaryMessenger)
    if let api = api {
      videoChannel.setMessageHandler { _, reply in
        let result = api.video()
        reply(wrapResult(result))
      }
    } else {
      videoChannel.setMessageHandler(nil)
    }
    /// Returns [String].
    /// Get current user id
    let getCurrentUserIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.getCurrentUserId", binaryMessenger: binaryMessenger)
    if let api = api {
      getCurrentUserIdChannel.setMessageHandler { _, reply in
        let result = api.getCurrentUserId()
        reply(wrapResult(result))
      }
    } else {
      getCurrentUserIdChannel.setMessageHandler(nil)
    }
    /// Returns [Void].
    /// Hangs up the "call".
    let confLeaveChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.confLeave", binaryMessenger: binaryMessenger)
    if let api = api {
      confLeaveChannel.setMessageHandler { _, reply in
        let result = api.confLeave()
        reply(wrapResult(result))
      }
    } else {
      confLeaveChannel.setMessageHandler(nil)
    }
    /// Returns [Boolean].
    /// True if the companion is in the call and shares video.
    /// Otherwise, returns false.
    let otherVideoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.otherVideo", binaryMessenger: binaryMessenger)
    if let api = api {
      otherVideoChannel.setMessageHandler { _, reply in
        let result = api.otherVideo()
        reply(wrapResult(result))
      }
    } else {
      otherVideoChannel.setMessageHandler(nil)
    }
    /// Returns [ConferenceStatus].
    /// Returns the current conference status.
    /// It can be one of the following:
    /// - [ConferenceStatus.on]
    /// - [ConferenceStatus.off]
    /// - [ConferenceStatus.waiting]
    let confStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.confStatus", binaryMessenger: binaryMessenger)
    if let api = api {
      confStatusChannel.setMessageHandler { _, reply in
        let result = api.confStatus()
        reply(wrapResult(result))
      }
    } else {
      confStatusChannel.setMessageHandler(nil)
    }
    /// Returns [Void].
    /// Switches the camera.
    let switchCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.switchCamera", binaryMessenger: binaryMessenger)
    if let api = api {
      switchCameraChannel.setMessageHandler { _, reply in
        api.switchCamera()
        reply(wrapResult(nil))
      }
    } else {
      switchCameraChannel.setMessageHandler(nil)
    }
  }
}
/// Generated class from Pigeon that represents Flutter messages that can be called from Swift.
class JyphoonReceiver {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  func onEvent(event eventArg: String, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonReceiver.onEvent", binaryMessenger: binaryMessenger)
    channel.sendMessage([eventArg]) { _ in
      completion()
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol JyphoonViewApi {
  func setFrame(width: Double, height: Double)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class JyphoonViewApiSetup {
  /// The codec used by JyphoonViewApi.
  /// Sets up an instance of `JyphoonViewApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: JyphoonViewApi?) {
    let setFrameChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonViewApi.setFrame", binaryMessenger: binaryMessenger)
    if let api = api {
      setFrameChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let widthArg = args[0] as! Double
        let heightArg = args[1] as! Double
        api.setFrame(width: widthArg, height: heightArg)
        reply(wrapResult(nil))
      }
    } else {
      setFrameChannel.setMessageHandler(nil)
    }
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: FlutterError) -> [Any?] {
  return [
    error.code,
    error.message,
    error.details
  ]
}
