// Autogenerated from Pigeon (v4.2.14), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif


/// Generated class from Pigeon.

enum CallType: Int {
  case oneToOne = 0
  case group = 1
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol JyphoonApi {
  /// Returns whether JC was inited.
  func isInited() -> Bool
  /// Initializes the engine. It is needed to set appKey before. Otherwise, it will fail.
  func initialize() -> Bool
  /// Sets appKey in order to have access to the Jyphoon API.
  func setAppKey(appKey: String)
  /// Sets the name that is visible to another participant(s).
  func setDisplayName(displayName: String)
  /// Sets account number. It acts like uuid. It launches login process.
  /// It is needed to set appKey before. Otherwise, it will fail.
  func setAccountNumber(accountNumber: String) -> Bool
  /// Sets the timeout for the call request.
  func setTimeout(timeout: Int32)
  /// Starts the "call".
  func call(confId: String, password: String, video: Bool, type: CallType) -> Bool
  /// Set Jyphoon backend server address.
  func setServerAddress(serverAddress: String)
  /// Starts or stops to send video
  func setVideo(video: Bool)
  /// Starts or stops to send audio.
  func setAudio(audio: Bool)
  /// Configures the speaker mode.
  func setSpeaker(speaker: Bool)
  /// True if the user is in the call and is not muted.
  /// Otherwise, returns false.
  func audio() -> Bool
  /// True if the companion is in the call and is not muted.
  /// Otherwise, returns false.
  func otherAudio() -> Bool
  /// True if the user is in the call and shares video.
  /// Otherwise, returns false.
  func video() -> Bool
  /// Get current user id
  func getCurrentUserId() -> String?
  /// Hangs up the "call".
  func leave() -> Bool
  /// True if the companion is in the call and shares video.
  /// Otherwise, returns false.
  func otherVideo() -> Bool
  /// Returns CallStatus.
  /// Returns the current call status.
  /// It can be one of the following:
  /// - CallStatus.on
  /// - CallStatus.off
  /// - CallStatus.waiting
  func callStatus() -> String
  /// Switches the camera (front/back)
  func switchCamera()
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class JyphoonApiSetup {
  /// The codec used by JyphoonApi.
  /// Sets up an instance of `JyphoonApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: JyphoonApi?) {
    /// Returns whether JC was inited.
    let isInitedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.isInited", binaryMessenger: binaryMessenger)
    if let api = api {
      isInitedChannel.setMessageHandler { _, reply in
        let result = api.isInited()
        reply(wrapResult(result))
      }
    } else {
      isInitedChannel.setMessageHandler(nil)
    }
    /// Initializes the engine. It is needed to set appKey before. Otherwise, it will fail.
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.initialize", binaryMessenger: binaryMessenger)
    if let api = api {
      initializeChannel.setMessageHandler { _, reply in
        let result = api.initialize()
        reply(wrapResult(result))
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    /// Sets appKey in order to have access to the Jyphoon API.
    let setAppKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.setAppKey", binaryMessenger: binaryMessenger)
    if let api = api {
      setAppKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let appKeyArg = args[0] as! String
        api.setAppKey(appKey: appKeyArg)
        reply(wrapResult(nil))
      }
    } else {
      setAppKeyChannel.setMessageHandler(nil)
    }
    /// Sets the name that is visible to another participant(s).
    let setDisplayNameChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.setDisplayName", binaryMessenger: binaryMessenger)
    if let api = api {
      setDisplayNameChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let displayNameArg = args[0] as! String
        api.setDisplayName(displayName: displayNameArg)
        reply(wrapResult(nil))
      }
    } else {
      setDisplayNameChannel.setMessageHandler(nil)
    }
    /// Sets account number. It acts like uuid. It launches login process.
    /// It is needed to set appKey before. Otherwise, it will fail.
    let setAccountNumberChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.setAccountNumber", binaryMessenger: binaryMessenger)
    if let api = api {
      setAccountNumberChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountNumberArg = args[0] as! String
        let result = api.setAccountNumber(accountNumber: accountNumberArg)
        reply(wrapResult(result))
      }
    } else {
      setAccountNumberChannel.setMessageHandler(nil)
    }
    /// Sets the timeout for the call request.
    let setTimeoutChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.setTimeout", binaryMessenger: binaryMessenger)
    if let api = api {
      setTimeoutChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let timeoutArg = args[0] as! Int32
        api.setTimeout(timeout: timeoutArg)
        reply(wrapResult(nil))
      }
    } else {
      setTimeoutChannel.setMessageHandler(nil)
    }
    /// Starts the "call".
    let callChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.call", binaryMessenger: binaryMessenger)
    if let api = api {
      callChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let confIdArg = args[0] as! String
        let passwordArg = args[1] as! String
        let videoArg = args[2] as! Bool
        let typeArg = CallType(rawValue: args[3] as! Int)!
        let result = api.call(confId: confIdArg, password: passwordArg, video: videoArg, type: typeArg)
        reply(wrapResult(result))
      }
    } else {
      callChannel.setMessageHandler(nil)
    }
    /// Set Jyphoon backend server address.
    let setServerAddressChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.setServerAddress", binaryMessenger: binaryMessenger)
    if let api = api {
      setServerAddressChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let serverAddressArg = args[0] as! String
        api.setServerAddress(serverAddress: serverAddressArg)
        reply(wrapResult(nil))
      }
    } else {
      setServerAddressChannel.setMessageHandler(nil)
    }
    /// Starts or stops to send video
    let setVideoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.setVideo", binaryMessenger: binaryMessenger)
    if let api = api {
      setVideoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let videoArg = args[0] as! Bool
        api.setVideo(video: videoArg)
        reply(wrapResult(nil))
      }
    } else {
      setVideoChannel.setMessageHandler(nil)
    }
    /// Starts or stops to send audio.
    let setAudioChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.setAudio", binaryMessenger: binaryMessenger)
    if let api = api {
      setAudioChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let audioArg = args[0] as! Bool
        api.setAudio(audio: audioArg)
        reply(wrapResult(nil))
      }
    } else {
      setAudioChannel.setMessageHandler(nil)
    }
    /// Configures the speaker mode.
    let setSpeakerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.setSpeaker", binaryMessenger: binaryMessenger)
    if let api = api {
      setSpeakerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let speakerArg = args[0] as! Bool
        api.setSpeaker(speaker: speakerArg)
        reply(wrapResult(nil))
      }
    } else {
      setSpeakerChannel.setMessageHandler(nil)
    }
    /// True if the user is in the call and is not muted.
    /// Otherwise, returns false.
    let audioChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.audio", binaryMessenger: binaryMessenger)
    if let api = api {
      audioChannel.setMessageHandler { _, reply in
        let result = api.audio()
        reply(wrapResult(result))
      }
    } else {
      audioChannel.setMessageHandler(nil)
    }
    /// True if the companion is in the call and is not muted.
    /// Otherwise, returns false.
    let otherAudioChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.otherAudio", binaryMessenger: binaryMessenger)
    if let api = api {
      otherAudioChannel.setMessageHandler { _, reply in
        let result = api.otherAudio()
        reply(wrapResult(result))
      }
    } else {
      otherAudioChannel.setMessageHandler(nil)
    }
    /// True if the user is in the call and shares video.
    /// Otherwise, returns false.
    let videoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.video", binaryMessenger: binaryMessenger)
    if let api = api {
      videoChannel.setMessageHandler { _, reply in
        let result = api.video()
        reply(wrapResult(result))
      }
    } else {
      videoChannel.setMessageHandler(nil)
    }
    /// Get current user id
    let getCurrentUserIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.getCurrentUserId", binaryMessenger: binaryMessenger)
    if let api = api {
      getCurrentUserIdChannel.setMessageHandler { _, reply in
        let result = api.getCurrentUserId()
        reply(wrapResult(result))
      }
    } else {
      getCurrentUserIdChannel.setMessageHandler(nil)
    }
    /// Hangs up the "call".
    let leaveChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.leave", binaryMessenger: binaryMessenger)
    if let api = api {
      leaveChannel.setMessageHandler { _, reply in
        let result = api.leave()
        reply(wrapResult(result))
      }
    } else {
      leaveChannel.setMessageHandler(nil)
    }
    /// True if the companion is in the call and shares video.
    /// Otherwise, returns false.
    let otherVideoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.otherVideo", binaryMessenger: binaryMessenger)
    if let api = api {
      otherVideoChannel.setMessageHandler { _, reply in
        let result = api.otherVideo()
        reply(wrapResult(result))
      }
    } else {
      otherVideoChannel.setMessageHandler(nil)
    }
    /// Returns CallStatus.
    /// Returns the current call status.
    /// It can be one of the following:
    /// - CallStatus.on
    /// - CallStatus.off
    /// - CallStatus.waiting
    let callStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.callStatus", binaryMessenger: binaryMessenger)
    if let api = api {
      callStatusChannel.setMessageHandler { _, reply in
        let result = api.callStatus()
        reply(wrapResult(result))
      }
    } else {
      callStatusChannel.setMessageHandler(nil)
    }
    /// Switches the camera (front/back)
    let switchCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonApi.switchCamera", binaryMessenger: binaryMessenger)
    if let api = api {
      switchCameraChannel.setMessageHandler { _, reply in
        api.switchCamera()
        reply(wrapResult(nil))
      }
    } else {
      switchCameraChannel.setMessageHandler(nil)
    }
  }
}
/// Generated class from Pigeon that represents Flutter messages that can be called from Swift.
class JyphoonReceiver {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  /// Called when the call status changes.
  func onEvent(event eventArg: String, data dataArg: [String?: Any?], completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JyphoonReceiver.onEvent", binaryMessenger: binaryMessenger)
    channel.sendMessage([eventArg, dataArg]) { _ in
      completion()
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CompanionViewApi {
  func setCompanionFrame(width: Double, height: Double)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CompanionViewApiSetup {
  /// The codec used by CompanionViewApi.
  /// Sets up an instance of `CompanionViewApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CompanionViewApi?) {
    let setCompanionFrameChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.CompanionViewApi.setCompanionFrame", binaryMessenger: binaryMessenger)
    if let api = api {
      setCompanionFrameChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let widthArg = args[0] as! Double
        let heightArg = args[1] as! Double
        api.setCompanionFrame(width: widthArg, height: heightArg)
        reply(wrapResult(nil))
      }
    } else {
      setCompanionFrameChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SelfViewApi {
  func setSelfFrame(width: Double, height: Double)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SelfViewApiSetup {
  /// The codec used by SelfViewApi.
  /// Sets up an instance of `SelfViewApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SelfViewApi?) {
    let setSelfFrameChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.SelfViewApi.setSelfFrame", binaryMessenger: binaryMessenger)
    if let api = api {
      setSelfFrameChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let widthArg = args[0] as! Double
        let heightArg = args[1] as! Double
        api.setSelfFrame(width: widthArg, height: heightArg)
        reply(wrapResult(nil))
      }
    } else {
      setSelfFrameChannel.setMessageHandler(nil)
    }
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: FlutterError) -> [Any?] {
  return [
    error.code,
    error.message,
    error.details
  ]
}
