name: jc
description: Jyphoon SDK for Flutter
version: 0.3.1

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  rxdart: ^0.27.7
  pigeon: ^4.2.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.michaellazebny.jyphoon.jc
        pluginClass: JcPlugin
      ios:
        pluginClass: JcPlugin
