name: jc
description: Jyphoon SDK for Flutter
version: 1.4.7

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  pigeon: ^4.2.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  sizzle_lints: ^1.0.10

flutter:
  plugin:
    platforms:
      android:
        package: com.michaellazebny.jyphoon.jc
        pluginClass: JcPlugin
      ios:
        pluginClass: JcPlugin
